#!/bin/bash --login
#PBS -N jacobi
#PBS -l select=6
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -A y14

echo Starting job

# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the direcotry that the job was submitted from
cd $PBS_O_WORKDIR

# Set the number of threads to 1
#   This prevents any system libraries from automatically 
#   using threading.
export OMP_NUM_THREADS=1

aprun -n 128 ./jacobi 1024 512
